[Service]
Host = "0.0.0.0"
Port = 50001
ConnectRetries = 3
Labels = []
OpenMsg = "device lte started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "0.0.0.0"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Logging]
EnableRemote = false
File = "./device-lte.log"
Level = "DEBUG"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "0.0.0.0"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "0.0.0.0"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "0.0.0.0"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

# Pre-define Devices
# [[DeviceList]]
#   Name = "Lte-device01"
#   Profile = "LTE光照度设备模板"
#   Description = "Example of Lte Device"
#   Labels = [ "industrial" ]
#   [DeviceList.Protocols]
#     [DeviceList.Protocols.lte]
#       Address = "127.0.0.1:8891"
#       Id = "171CB7408463"
#   [[DeviceList.AutoEvents]]
#     Frequency = "30s"
#     OnChange = false
#     Resource = "value"